feat/i18n: add translations for en-US, zh-CN and zh-TW
AOSC-Dev/systemd-boot-friend-rs pull request #3
Opened 2021-08-27 06:42 UTC by OriginCode

2021-08-27 06:46 UTC, MingcongBai requested changes

2021-08-27 06:46 UTC, MingcongBai commented on i18n/zh-CN/systemd_boot_friend_rs.ftl
> +conf_default = {$conf_path} 不存在！创建默认配置文件中……
${conf_path} 不存在！正在创建默认配置文件 ...

2021-08-27 06:46 UTC, MingcongBai commented on i18n/zh-CN/systemd_boot_friend_rs.ftl
> +invalid_esp = 不正确的 ESP_MOUNTPOINT
ESP 挂载点不正确

2021-08-27 06:46 UTC, MingcongBai commented on i18n/zh-CN/systemd_boot_friend_rs.ftl
> +empty_list = 列表为空
什么列表？

2021-08-27 06:46 UTC, MingcongBai commented on i18n/zh-CN/systemd_boot_friend_rs.ftl
> +invalid_num = 不正确的内核序号
什么？

2021-08-27 06:46 UTC, MingcongBai commented on i18n/zh-CN/systemd_boot_friend_rs.ftl
> +invalid_kernel_filename = 不正确的内核文件名
内核文件名不正确

2021-08-27 06:46 UTC, MingcongBai commented on i18n/zh-CN/systemd_boot_friend_rs.ftl
> +info_path_not_exist = {$path} 不存在。无事可做。
推敲下“无事可做”，这太英文

2021-08-27 06:46 UTC, MingcongBai commented on i18n/zh-CN/systemd_boot_friend_rs.ftl
> +    如果您想使用 systemd-boot，请首先执行 `systemd-boot-friend init`。
请先执行 *

2021-08-27 06:46 UTC, MingcongBai commented on i18n/zh-CN/systemd_boot_friend_rs.ftl
> +initialize = 初始化 systemd-boot 中...
正在初始化 systemd-boot ...

2021-08-27 06:46 UTC, MingcongBai commented on i18n/zh-CN/systemd_boot_friend_rs.ftl
> +create_folder = 建立 friend 目录结构中...
别中了，这不中

2021-08-27 06:46 UTC, MingcongBai commented on i18n/zh-CN/systemd_boot_friend_rs.ftl
> +ask_overwrite = {$entry} 已存在。是否覆盖？
“是否覆盖”应改为更完整的语句

2021-08-27 08:00 UTC, MingcongBai approved these changes

2021-08-29 11:06 UTC, NeoChen1024 commented on i18n/zh-TW/systemd_boot_friend_rs.ftl
> +    執行 `systemd-boot-friend init` 即可安裝並配置 systemd-boot。
s/可安裝並配置/可安裝並設定/

2021-08-29 11:06 UTC, NeoChen1024 commented on i18n/zh-TW/systemd_boot_friend_rs.ftl
> +empty_list = 內核列表為空
Kernel => 核心

2021-08-29 11:06 UTC, NeoChen1024 commented on i18n/zh-TW/systemd_boot_friend_rs.ftl
> +invalid_kernel_filename = 內核檔案名不正確
檔案名稱

2021-08-29 13:56 UTC, merged