i18n: shorten the prompts
AOSC-Dev/systemd-boot-friend-rs pull request #7
Opened 2022-04-21 23:50 UTC by OriginCode

Shorten the prompts to enhance the user experience of reading them.

2022-04-21 23:58 UTC, liushuyu commented on i18n/en-US/systemd_boot_friend_rs.ftl
> +ask_current_root = Use as default systemd-boot boot arguments? (root={$root} rw)
```suggestion
ask_empty_bootarg = Auto generate the boot arguments?
ask_current_bootarg = Default boot arguments?
ask_current_root = Default boot arguments? (root={$root} rw)
```

2022-04-21 23:58 UTC, liushuyu commented on i18n/en-US/systemd_boot_friend_rs.ftl
> +ask_set_default = Set {$kernel} as default boot entry?
```suggestion
ask_set_default = Set {$kernel} as the default boot entry?
```

2022-04-21 23:58 UTC, liushuyu commented on i18n/en-US/systemd_boot_friend_rs.ftl
>      search your {$src_path} directory for kernels and register them in systemd-boot
```suggestion
    search your `{$src_path}` directory for kernels and register them in systemd-boot
```

2022-04-21 23:58 UTC, liushuyu commented on i18n/en-US/systemd_boot_friend_rs.ftl
>      `systemd-boot-friend update`.
It's recommended to remove the "If not, you could always do so by running `systemd-boot-friend update`"  portion from this prompt.

Instead, add a logic to print this sentence when the user selected no.

```
[...] > no

You can add them later by running `systemd-boot-friend update`.
```

2022-04-22 23:35 UTC, MingcongBai requested changes

2022-04-22 23:35 UTC, MingcongBai commented on i18n/en-US/systemd_boot_friend_rs.ftl
> +ask_empty_bootarg = Auto generate the boot arguments?
Remove "the"

2022-04-22 23:35 UTC, MingcongBai commented on i18n/en-US/systemd_boot_friend_rs.ftl
> +ask_empty_bootarg = Auto generate the boot arguments?
Replace "Auto" with "Automatically"

2022-04-22 23:35 UTC, MingcongBai commented on i18n/en-US/systemd_boot_friend_rs.ftl
> +ask_current_bootarg = Use the above as the default systemd-boot boot arguments?
Use the kernel parameters above as systemd-boot defaults?

2022-04-22 23:35 UTC, MingcongBai commented on i18n/en-US/systemd_boot_friend_rs.ftl
> +ask_current_root = Use `root={$root} rw` as the default systemd-boot boot arguments?
```
Append `root={$root} rw` to the default systemd-boot kernel parameters?
```

2022-04-22 23:35 UTC, MingcongBai commented on i18n/en-US/systemd_boot_friend_rs.ftl
> +ask_empty_bootarg = Auto generate the boot arguments?
Replace "boot arguments" with "kernel parameters"

2022-04-22 23:47 UTC, OriginCode commented on i18n/en-US/systemd_boot_friend_rs.ftl
> +ask_current_root = Use `root={$root} rw` as the default systemd-boot boot arguments?
It's not append.

2022-04-23 04:53 UTC, MingcongBai requested changes

2022-04-23 04:53 UTC, MingcongBai commented on i18n/zh-CN/systemd_boot_friend_rs.ftl
> +    后，您依旧可以在 EFI 启动管理器中访问其他已安装的启动引导器，如 GRUB 或 Windows 启动
“您依旧可以从 EFI 启动管理器访问其他启动引导器，……”

2022-04-23 04:53 UTC, MingcongBai commented on i18n/zh-CN/systemd_boot_friend_rs.ftl
> +skip_update = 您可以在之后执行 `systemd-boot-friend update` 以加入启动项。
您可以随时运行 `systemd-boot-friend update` 来登记启动项。

2022-04-23 04:53 UTC, MingcongBai commented on i18n/zh-CN/systemd_boot_friend_rs.ftl
> +ask_overwrite = {$entry} 已存在。覆盖该文件？
{$entry} 已存在。是否覆盖该文件？

2022-04-23 04:53 UTC, MingcongBai commented on i18n/zh-CN/systemd_boot_friend_rs.ftl
> +ask_set_default = 将 {$kernel} 设为默认启动项？
这类问题一律加“是否”开头，否则文法不通

2022-04-23 04:53 UTC, MingcongBai commented on i18n/zh-CN/systemd_boot_friend_rs.ftl
> +select_default = 默认启动的内核
默认内核

2022-04-23 04:53 UTC, MingcongBai commented on i18n/zh-CN/systemd_boot_friend_rs.ftl
> +input_timeout = 启动菜单等待时长（秒）
“显示时长”会更好

2022-04-23 06:34 UTC, NeoChen1024 commented
zh_TW checked: OK

2022-04-23 06:35 UTC, merged